const PROJECT_NAME = "Prepaid Gas"
const PROJECT_VERSION = "0.0.1"
const CHAIN_ID = 31337
const VALIDATOR_THRESHOLD = 2
const VALIDATORS = []

module.exports = {
  PROJECT_NAME,
  PROJECT_VERSION,
  CHAIN_ID,
  VALIDATOR_THRESHOLD,
  VALIDATORS,
}
