// @dev constants for testing
const LOCKED_GUARANTEE_PER_GAS = 100
const INITIAL_EXECUTOR_REWARD = 200
const GAS_AMOUNT = 20000000
const GAS_COST = 100
const TOTAL_TEST_ORDERS_AMOUNT = 300

const TOKEN_BASE = 10000000
const DENOM = 10000
const SYSTEM_FEE = 1000 // 100 = 1%
const TOKEN_LINK = ""

module.exports = {
  LOCKED_GUARANTEE_PER_GAS,
  INITIAL_EXECUTOR_REWARD,
  GAS_AMOUNT,
  GAS_COST,
  SYSTEM_FEE,
  TOKEN_BASE,
  TOTAL_TEST_ORDERS_AMOUNT,
  TOKEN_LINK,
  DENOM,
}
